### ISSUE TITLE
깃헙과 마크다운 사용법

### ISSUE THREAD

**Issue by ChoiKangM** [haedal-with-knu/instuctorTraining#1]

**Comment by ChoiKangM** [comment]
최강민
https://github.com/kei01138/markdownExample.git

**Comment by KNUjun** [comment]
이준기
https://github.com/KNUjun/gitExample.git

**Comment by LJBang** [comment]
이준병
https://github.com/LJBang/learn-markdown.git

**Comment by ewsn1593** [comment]
신준철
https://github.com/ewsn1593/Markdown.git

**Comment by ghost** [comment]
한영민
https://github.com/PPOMPPLE/1st-instuctorTraining

**Comment by Joo-ra-n** [comment]
김주원
https://github.com/Joo-ra-n/markdown

**Comment by ChuJungHo** [comment]
추정호
https://github.com/ChuJungHo/EasyMarkdown.git

**Comment by swff07183** [comment]
홍성목
https://github.com/swff07183/MarkdownExample.git

**Comment by dnjsrb0710** [comment]
이원규
https://github.com/dnjsrb0710/markdownexample#%EC%97%AC%EA%B8%B0%EB%8A%94-%EB%91%90%EB%B2%88%EC%A8%B0-%ED%97%A4%EB%93%9C

**Comment by wotjd0715** [comment]
박재성
https://github.com/wotjd0715/markdown

**Comment by GWANNYUNG** [comment]
변관녕
https://github.com/GWANNYUNG/markdown

**Comment by GWANNYUNG** [comment]
변관녕
https://github.com/GWANNYUNG/markdown

**Comment by Min-hye-OK** [comment]
https://github.com/Min-hye-OK/markdown

**Comment by SH0909** [comment]
https://github.com/SH0909/markdown

**Comment by miinji** [comment]
박민지

https://github.com/miinji/markdown

**Comment by lymiere** [comment]
권남우

https://github.com/lymiere/markdown

**Comment by hyo-hyun** [comment]
조효현

https://github.com/hyo-hyun/Markdown__

**Comment by hyo-hyun** [comment]
조효현

https://github.com/hyo-hyun/Markdown__

**Comment by hyo-hyun** [comment]
조효현

https://github.com/hyo-hyun/Markdown__

**Comment by hyo-hyun** [comment]
https://github.com/hyo-hyun/Markdown__
