### ISSUE TITLE
자기소개페이지

### ISSUE THREAD

**Issue by ChoiKangM** [haedal-with-knu/instuctorTraining#2]

**Comment by KNUjun** [comment]
이준기
https://knujun.github.io

**Comment by ChuJungHo** [comment]
추정호
https://chujungho.github.io/

**Comment by LJBang** [comment]
이준병
https://LJBang.github.io/

**Comment by ChoiKangM** [comment]
해달
https://haedal-programming.github.io

**Comment by ghost** [comment]
한영민
https://ppompple.github.io/

**Comment by ewsn1593** [comment]
신준철
https://ewsn1593.github.io/

**Comment by GWANNYUNG** [comment]
변관녕
https://github.com/haedal-with-knu/instuctorTraining/issues/2

**Comment by GWANNYUNG** [comment]
변관녕
https://gwannyung.github.io/

**Comment by SH0909** [comment]
https://SH0909.github.io/

**Comment by miinji** [comment]
http://miinji.github.io/

**Comment by lymiere** [comment]
https://lymiere.github.io/

**Comment by hyo-hyun** [comment]
https://hyo-hyun.github.io/

**Comment by wotjd0715** [comment]
https://wotjd0715.github.io/

**Comment by Joo-ra-n** [comment]
https://joo-ra-n.github.io/

**Comment by oyoungsun** [comment]
https://oyoungsun.github.io/

**Comment by Climier-code** [comment]
강종연
https://climier-code.github.io/

**Comment by BocchiTheCoding** [comment]
임재성
https://ingkuang.github.io/

**Comment by johm3801** [comment]
https://johm3801.github.io/

**Comment by swff07183** [comment]
https://swff07183.github.io/

**Comment by jaesseong** [comment]
김재성
https://jaeseong4156.github.io/

**Comment by impulsive526** [comment]
이순원

impulsive526.github.io

**Comment by chochaewon** [comment]
https://chochaewon.github.io/chaewon.github.io/

**Comment by Kim-Jiwan** [comment]
https://kim-jiwan.github.io/

**Comment by cometrue00** [comment]
최성주
https://cometrue00.github.io/

**Comment by horkheimer8** [comment]
https://github.com/horkheimer8/horkheimer8.github.io
드뎌...

**Comment by ChoiKangM** [comment]
부세현
https://Boo-SeHyeon.github.io
https://github.com/Boo-SeHyeon/Boo-SeHyeon.github.io

**Comment by ChoiKangM** [comment]
채지영
https://horkheimer8.github.io
https://github.com/horkheimer8/horkheimer8.github.io
