### ISSUE TITLE
자기소개카드 만들기

### ISSUE THREAD

**Issue by ChoiKangM** [haedal-with-knu/instuctorTraining#22]
이름, 레포링크, 이미지 넣어주세요

**Comment by SH0909** [comment]
박세희 https://github.com/SH0909/MypageCard
![자기소개카드](https://user-images.githubusercontent.com/48480810/89370936-e89ed180-d71c-11ea-9ddd-756d629ccbc9.PNG)

**Comment by horkheimer8** [comment]
채지영 [레포](https://github.com/horkheimer8/myCard)

<img width="535" alt="Screenshot 2020-08-05 at 13 37 40" src="https://user-images.githubusercontent.com/45495211/89372335-d757c400-d720-11ea-9186-ebaecf1c0ab6.png">

**Comment by LJBang** [comment]
이준병 [여기](https://github.com/LJBang/ljbang.github.io/blob/master/card/card.html)
![card](https://user-images.githubusercontent.com/48755145/89373571-058ad300-d724-11ea-97a6-6d8f8cc4d91c.PNG)

**Comment by Climier-code** [comment]
강종연 [_레포_](https://github.com/Climier-code/INTRODUCECARD.climier.github.io.git)
<img width="224" alt="주석 2020-08-05 141112" src="https://user-images.githubusercontent.com/55488800/89374261-d37a7080-d725-11ea-9db6-d266b7c5d01e.png">

**Comment by Joo-ra-n** [comment]
김주원 [안녕](https://joo-ra-n.github.io)
![teemo](https://user-images.githubusercontent.com/48755218/89380646-d4fe6580-d732-11ea-8acc-d3df262a0f13.PNG)

**Comment by chochaewon** [comment]
조채원 [레포](https://github.com/chochaewon/chaewoncard.git)
![1111](https://user-images.githubusercontent.com/55488674/89382474-e137f200-d735-11ea-97c8-c9b019c320c3.PNG)

**Comment by johm3801** [comment]
조혜민 [레포](https://github.com/johm3801/mynamecard)
![image](https://user-images.githubusercontent.com/67828575/89386793-8c4baa00-d73c-11ea-9032-c18be425cbdb.png)

**Comment by oyoungsun** [comment]
오영선 [오늘은 열심히했어요](https://github.com/oyoungsun/mycard.github.io.git)
<img width="652" alt="20200805_165733" src="https://user-images.githubusercontent.com/63745627/89387059-ecdae700-d73c-11ea-94f8-fe57c6770550.png">

**Comment by impulsive526** [comment]
이순원
 [.](https://github.com/impulsive526/my_card) 
![image](https://user-images.githubusercontent.com/67626880/89392769-ed777b80-d744-11ea-8a00-b22d2dba0c73.png)

**Comment by BocchiTheCoding** [comment]
임재성 https://github.com/ingkuang/introcard
![ee](https://user-images.githubusercontent.com/11649387/89418410-fa0eca80-d76a-11ea-820b-358249399be9.png)

**Comment by swff07183** [comment]
홍성목 [링크](https://github.com/swff07183/swff07183.github.io/blob/master/card.html)

![card](https://user-images.githubusercontent.com/44836393/89426907-9c33b000-d775-11ea-8381-afccc50102ad.png)

**Comment by Kim-Jiwan** [comment]
![image](https://user-images.githubusercontent.com/65444464/89434690-cdfd4480-d77e-11ea-9934-c94a9154b926.png)
김지완 https://github.com/Kim-Jiwan/Kim-Jiwan.github.io

**Comment by cometrue00** [comment]
최성주 [REPO](https://github.com/cometrue00/Mycard)
![Mycard](https://user-images.githubusercontent.com/55488684/89476434-a382aa00-d7c5-11ea-8a93-6a618187b99c.jpg)

**Comment by jaesseong** [comment]
![자기소개 카드](https://user-images.githubusercontent.com/62880445/89479062-d1b7b800-d7cc-11ea-8e4a-75508078f31d.PNG)

김재성 https://github.com/Jaeseong4156/IntroduceCard

**Comment by Boo-SeHyeon** [comment]
부세현 https://github.com/Boo-SeHyeon/Boo-Sehyeoncard.github.io.git
![image](https://user-images.githubusercontent.com/55488812/89478995-a2a14680-d7cc-11ea-8de4-0b9c12b3df48.png)
