### ISSUE TITLE
채_오차

### ISSUE THREAD

**Issue by impulsive526** [haedal-with-knu/instuctorTraining#23]
오영선 님, 차민준 님 과제 제출은 여기에 해주시면 됩니다.

각 일차(1일차~30일차)의 내용이 끝날 때마다 완성 화면 캡쳐 후 업로드 해주시면 됩니다. (책의 앞부분 학습 계획표 참조)

---------------------------------------
ex)5일차까지 완료했을 때

104페이지까지 완료했습니다.

3일차: (3일차의 게시판 만들기 사진 업로드)

5일차: (부트스트랩 사용해서 꾸민 사진 업로드)

---------------------------------------
배포(25일차 이후)부터는 막히면 그만 두셔도 괜찮습니다. 그런 경우 24일차(깃・깃허브)까지 완성하고 깃허브 주소 업로드를 최종 과제로 제출해주시면 됩니다.

**Comment by oyoungsun** [comment]
![2 6](https://user-images.githubusercontent.com/63745627/105750149-b19cd080-5f87-11eb-9ede-306395c9eeb7.png)

3일차까지 완료

**Comment by oyoungsun** [comment]
![2 10](https://user-images.githubusercontent.com/63745627/105960958-3f300b80-60c1-11eb-97c3-c318873cc506.png)
 

2.10까지 완료

**Comment by oyoungsun** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/63745627/107464237-30f2ec80-6ba3-11eb-89e6-1d83ec5a2c8b.png)

https://github.com/oyoungsun/pybo
4.03까지 완료
