### ISSUE TITLE
이_임장

### ISSUE THREAD

**Issue by impulsive526** [haedal-with-knu/instuctorTraining#24]
임재성 님, 장혜원 님 과제 제출은 여기에 해주시면 됩니다.

각 일차(1일차~30일차)의 내용이 끝날 때마다 완성 화면 캡쳐 후 업로드 해주시면 됩니다. (책의 앞부분 학습 계획표 참조)

---------------------------------------
ex)5일차까지 완료했을 때

104페이지까지 완료했습니다.

3일차: (3일차의 게시판 만들기 사진 업로드)

5일차: (부트스트랩 사용해서 꾸민 사진 업로드)

---------------------------------------
배포(25일차 이후)부터는 막히면 그만 두셔도 괜찮습니다. 그런 경우 24일차(깃・깃허브)까지 완성하고 깃허브 주소 업로드를 최종 과제로 제출해주시면 됩니다.

**Comment by hai-ley** [comment]
<img width="960" alt="2021-02-06 (5)" src="https://user-images.githubusercontent.com/71762106/107115054-4a4b1e80-68ad-11eb-9567-b0a06f524b60.png">

12일차 03-5까지 완료했습니다.

**Comment by BocchiTheCoding** [comment]
![ok](https://user-images.githubusercontent.com/11649387/107152246-36391700-69aa-11eb-90be-bd19c11622ea.png)
3-10까지 했습니다
