### ISSUE TITLE
신_문조

### ISSUE THREAD

**Issue by impulsive526** [haedal-with-knu/instuctorTraining#25]
문정원 님, 조채원 님 과제 제출은 여기에 해주시면 됩니다.

각 일차(1일차~30일차)의 내용이 끝날 때마다 완성 화면 캡쳐 후 업로드 해주시면 됩니다. (책의 앞부분 학습 계획표 참조)

---------------------------------------
ex)5일차까지 완료했을 때

104페이지까지 완료했습니다.

3일차: (3일차의 게시판 만들기 사진 업로드)

5일차: (부트스트랩 사용해서 꾸민 사진 업로드)

---------------------------------------
배포(25일차 이후)부터는 막히면 그만 두셔도 괜찮습니다. 그런 경우 24일차(깃・깃허브)까지 완성하고 깃허브 주소 업로드를 최종 과제로 제출해주시면 됩니다.

**Comment by gaarden** [comment]
![3일차(2 6)](https://user-images.githubusercontent.com/72001106/106274892-56fdc000-6278-11eb-8cab-023249fad600.JPG)
3일차(2.6)까지 완료했습니다.

**Comment by gaarden** [comment]
![4일차(2 7)](https://user-images.githubusercontent.com/72001106/106287508-36d6fc80-628a-11eb-9651-c43dec6de26c.JPG)
4일차(2.7)까지 완료했습니다.

**Comment by gaarden** [comment]
![5일차(2 8)](https://user-images.githubusercontent.com/72001106/106287552-43f3eb80-628a-11eb-93d8-6f8c08de30f3.JPG)
5일차(2.8)까지 완료했습니다.

**Comment by gaarden** [comment]
![7일차(2 10)](https://user-images.githubusercontent.com/72001106/106287606-50784400-628a-11eb-978a-e343799b4dda.JPG)
7일차(2.10)까지 완료했습니다.

**Comment by gaarden** [comment]
![9일차(3 2)](https://user-images.githubusercontent.com/72001106/106294968-3131e480-6293-11eb-9c88-bac63fe9d147.JPG)
9일차(3.2)까지 완료했습니다.

**Comment by gaarden** [comment]
![10일차(3 3)](https://user-images.githubusercontent.com/72001106/106345118-3a519e80-62f1-11eb-8b36-d249855e4023.JPG)
10일차(3.3)까지 완료했습니다.

**Comment by gaarden** [comment]
![11일차(3 4)](https://user-images.githubusercontent.com/72001106/106345122-463d6080-62f1-11eb-88be-17595f454262.JPG)
11일차(3.4)까지 완료했습니다.

**Comment by gaarden** [comment]
![12일차(3 5)](https://user-images.githubusercontent.com/72001106/106345130-52c1b900-62f1-11eb-8c62-dec00e0582af.JPG)
12일차(3.5)까지 완료했습니다. (p.153)

**Comment by gaarden** [comment]
![13일차(3 6)](https://user-images.githubusercontent.com/72001106/106360354-4f631780-635b-11eb-8c1f-95797a2d465a.JPG)
13일차(3.6)까지 완료했습니다.

**Comment by gaarden** [comment]
![14일차(3 7)](https://user-images.githubusercontent.com/72001106/106360362-5db13380-635b-11eb-93cd-fd6c29aac05c.JPG)
14일차(3.7)까지 완료했습니다.

**Comment by gaarden** [comment]
![15일차(3 8)](https://user-images.githubusercontent.com/72001106/106360373-6ace2280-635b-11eb-9729-c51e6b272625.JPG)
15일차(3.8)까지 완료했습니다.(p.172)

**Comment by chochaewon** [comment]
![2일차](https://user-images.githubusercontent.com/55488674/106383600-52691100-640a-11eb-83c5-4e20b6e63d90.png)
2일차(~p.74)까지 완료했습니다

**Comment by chochaewon** [comment]
![5일차](https://user-images.githubusercontent.com/55488674/106383624-77f61a80-640a-11eb-99d1-fcd064687617.png)
5일차(~p.104)까지 완료했습니다

**Comment by chochaewon** [comment]
![7일차](https://user-images.githubusercontent.com/55488674/106383644-86dccd00-640a-11eb-8f85-61524831d4cd.png)
7일차(~p.121)까지 완료했습니다

**Comment by chochaewon** [comment]
![10일차](https://user-images.githubusercontent.com/55488674/106383659-93612580-640a-11eb-87ee-8a17244c742f.png)
10일차(~p.141)까지 완료했습니다

**Comment by chochaewon** [comment]
![12일차](https://user-images.githubusercontent.com/55488674/106383673-9fe57e00-640a-11eb-9838-52b7a3449d28.png)
12일차(~p.153)까지 완료했습니다

**Comment by chochaewon** [comment]
![13일차](https://user-images.githubusercontent.com/55488674/106383687-ad9b0380-640a-11eb-848d-68ee4762a7ff.png)
13일차(~p.160)까지 완료했습니다

**Comment by chochaewon** [comment]
![14일차](https://user-images.githubusercontent.com/55488674/106383702-bc81b600-640a-11eb-9020-7cf6c748c7da.png)
14일차(~p.169)까지 완료했습니다

**Comment by chochaewon** [comment]
![15일차](https://user-images.githubusercontent.com/55488674/106383711-c73c4b00-640a-11eb-9db6-7eabe4b26659.png)
15일차(~p.172)까지 완료했습니다

**Comment by chochaewon** [comment]
![16일차](https://user-images.githubusercontent.com/55488674/106384348-bc36ea00-640d-11eb-8363-985049d52ed0.png)
16일차(~p.188)까지 완료했습니다

**Comment by gaarden** [comment]
![16일차(3 9)](https://user-images.githubusercontent.com/72001106/106493871-11055e00-64fd-11eb-89c2-55bda08067e9.JPG)
16일차(3.9)까지 완료했습니다.

**Comment by gaarden** [comment]
![17일차(3 10)](https://user-images.githubusercontent.com/72001106/106493916-1f537a00-64fd-11eb-8891-256e7d35c6e7.JPG)
17일차(3.10)까지 완료했습니다.
18일차(3.11)까지 완료했습니다.(p.208)

**Comment by gaarden** [comment]
![19일차(3 12)](https://user-images.githubusercontent.com/72001106/106566882-46995e00-6574-11eb-9195-19a8c772233b.JPG)
19일차(3.12)까지 완료했습니다.

**Comment by gaarden** [comment]
![20일차(3 13)](https://user-images.githubusercontent.com/72001106/106566907-52852000-6574-11eb-8937-954be79f079d.JPG)
20일차(3.13)까지 완료했습니다.

**Comment by gaarden** [comment]
![21일차(3 14)](https://user-images.githubusercontent.com/72001106/106566937-5d3fb500-6574-11eb-845b-dc287328c151.JPG)
21일차(3.14)까지 완료했습니다.

**Comment by gaarden** [comment]
![22일차(3 15)](https://user-images.githubusercontent.com/72001106/106566972-67fa4a00-6574-11eb-9ab9-b3c1f060dda6.JPG)
22일차(3.15)까지 완료했습니다. (p.243)

**Comment by gaarden** [comment]
https://github.com/gaarden/pybo

24일차(4.3)까지 완료했습니다. (p.262)
