### ISSUE TITLE
박_정조

### ISSUE THREAD

**Issue by impulsive526** [haedal-with-knu/instuctorTraining#26]
정예지 님, 조혜민 님 과제 제출은 여기에 해주시면 됩니다.

각 일차(1일차~30일차)의 내용이 끝날 때마다 완성 화면 캡쳐 후 업로드 해주시면 됩니다. (책의 앞부분 학습 계획표 참조)

---------------------------------------
ex)5일차까지 완료했을 때

104페이지까지 완료했습니다.

3일차: (3일차의 게시판 만들기 사진 업로드)

5일차: (부트스트랩 사용해서 꾸민 사진 업로드)

---------------------------------------
배포(25일차 이후)부터는 막히면 그만 두셔도 괜찮습니다. 그런 경우 24일차(깃・깃허브)까지 완성하고 깃허브 주소 업로드를 최종 과제로 제출해주시면 됩니다.

**Comment by johm3801** [comment]
![3일차](https://user-images.githubusercontent.com/67828575/105895884-74087800-6059-11eb-915d-894999e6905f.png)
3일차까지(96p) 완료했습니다.

**Comment by johm3801** [comment]
![5-1](https://user-images.githubusercontent.com/67828575/105979341-ebc8b800-60d6-11eb-80c6-dcad3f80c071.PNG)
![5-2](https://user-images.githubusercontent.com/67828575/105979343-ec614e80-60d6-11eb-808d-c97ea1857bfc.PNG)
5일차(104p) 완료했습니다.

**Comment by johm3801** [comment]
![7](https://user-images.githubusercontent.com/67828575/105993712-0f492e00-60ea-11eb-9921-b03b0011fbe2.PNG)
7일차(121p) 완료했습니다.

**Comment by johm3801** [comment]
![8일차](https://user-images.githubusercontent.com/67828575/106092735-44995e80-6172-11eb-8387-6ffe46d17120.PNG)
8일차(129p) 완료했습니다.

**Comment by johm3801** [comment]
![9](https://user-images.githubusercontent.com/67828575/106233989-29465600-623b-11eb-8b51-5e760811d1ec.PNG)
9일차(137p) 완료했습니다.

**Comment by johm3801** [comment]
![10](https://user-images.githubusercontent.com/67828575/106234877-e4232380-623c-11eb-88be-eb8d10feae3a.PNG)
10일차(141p) 완료했습니다.

**Comment by johm3801** [comment]
![11](https://user-images.githubusercontent.com/67828575/106235210-a07ce980-623d-11eb-8b5b-08f61f2f42ee.PNG)
11일차(142p) 완료했습니다.

**Comment by johm3801** [comment]
![12](https://user-images.githubusercontent.com/67828575/106237946-41ba6e80-6243-11eb-8448-feaab10e5498.PNG)
12일차(153p) 완료했습니다.

**Comment by johm3801** [comment]
![13](https://user-images.githubusercontent.com/67828575/106243059-007a8c80-624c-11eb-9822-256cc6ca2e29.PNG)
13일차(160p) 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106307354-95a87000-62a2-11eb-87c8-e5de84a3973e.png)
1일차(37p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106307394-a78a1300-62a2-11eb-9121-6ec43cdd9b95.png)
2일차(74p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106309719-deadf380-62a5-11eb-97b0-2c702bc7b91c.png)
3일차(96p)까지 완성했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106311623-c7243a00-62a8-11eb-8053-b98d70466ce6.png)
4일차(99p)까지 완성했습니다.

**Comment by johm3801** [comment]
![14](https://user-images.githubusercontent.com/67828575/106459643-80ffee00-64d5-11eb-8da5-4fcc3acc030e.PNG)
14일차(169p) 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/106461166-bf96a800-64d7-11eb-99c3-a7ec1c005018.png)
15일차(172p) 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/106475583-6e8faf80-64e9-11eb-87a7-52f66e05d611.png)
16일차(188p) 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106493249-3c3b7d80-64fc-11eb-8de2-7f58a58179c4.png)
5일차(104p)완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106493300-4e1d2080-64fc-11eb-9317-47b3219681d3.png)
7일차(121p)완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/106636090-e8489b80-65c4-11eb-90b2-59ad83e9c411.png)
17일차(200p) 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106734801-c992e500-6656-11eb-8459-1765f59d1e0b.png)
8일차(129p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106734860-dc0d1e80-6656-11eb-9218-36a356895ed3.png)
9일차(137p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/106735021-0b239000-6657-11eb-8418-c1e540767238.png)
10일차(139p)까지 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/106998730-50b39a80-67c8-11eb-852b-9fd5fc15f8d1.png)
19일차(220p) 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/107000522-5e1e5400-67cb-11eb-91a7-a66d7aa98834.png)
20일차(226p) 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/107001214-9c684300-67cc-11eb-91b0-9765ca5b503e.png)
21일차(231p) 완료했습니다.

**Comment by johm3801** [comment]
![image](https://user-images.githubusercontent.com/67828575/107004757-14853780-67d2-11eb-96d4-09d7f40b6dc2.png)
22일차(243p) 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/107005428-097ed700-67d3-11eb-9c7d-4bbfc001a9b0.png)
11일차(142p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/107005487-1e5b6a80-67d3-11eb-89b2-0e232bdefdec.png)
12일일차(153p)까지 완료했습니다.

**Comment by johm3801** [comment]
https://github.com/johm3801/pybo
24일차까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/107030089-6f7b5680-67f3-11eb-8199-996199c70c9f.png)
![image](https://user-images.githubusercontent.com/71762325/107030111-786c2800-67f3-11eb-8f09-d38db51576c9.png)
14일차(169p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/107111384-13680f00-6893-11eb-99e8-c25c054ca651.png)
15일차(172p)까지 완료했습니다.

**Comment by yeji-jeong** [comment]
![image](https://user-images.githubusercontent.com/71762325/107155149-2295ac80-69ba-11eb-87f6-012ade6f3092.png)
16일차(188p)까지 완료했습니다.
