### ISSUE TITLE
김_옥이

### ISSUE THREAD

**Issue by impulsive526** [haedal-with-knu/instuctorTraining#27]
옥명주 님, 이정민 님 과제 제출은 여기에 해주시면 됩니다.

각 일차(1일차~30일차)의 내용이 끝날 때마다 완성 화면 캡쳐 후 업로드 해주시면 됩니다. (책의 앞부분 학습 계획표 참조)

---------------------------------------
ex)5일차까지 완료했을 때

104페이지까지 완료했습니다.

3일차: (3일차의 게시판 만들기 사진 업로드)

5일차: (부트스트랩 사용해서 꾸민 사진 업로드)

---------------------------------------
배포(25일차 이후)부터는 막히면 그만 두셔도 괜찮습니다. 그런 경우 24일차(깃・깃허브)까지 완성하고 깃허브 주소 업로드를 최종 과제로 제출해주시면 됩니다.

**Comment by dhraudwn** [comment]
![1일차](https://user-images.githubusercontent.com/62053412/106265022-cd46f600-6269-11eb-9ffa-0e3bca9cfde2.png)
![2일차](https://user-images.githubusercontent.com/62053412/106265025-ce782300-6269-11eb-9a49-9e848a555a6b.png)
![3일차](https://user-images.githubusercontent.com/62053412/106265027-ce782300-6269-11eb-8c52-f6b15096e82e.png)
![4일차](https://user-images.githubusercontent.com/62053412/106265029-cf10b980-6269-11eb-98ff-a82c301bd43c.png)
![5일차](https://user-images.githubusercontent.com/62053412/106265030-cf10b980-6269-11eb-85d1-c98c129edd40.png)
5일차 까지 완료했습니다

**Comment by dhraudwn** [comment]
![9일차](https://user-images.githubusercontent.com/62053412/106364635-c3111e80-6373-11eb-95bc-985119251419.png)
![10일차](https://user-images.githubusercontent.com/62053412/106364636-c3a9b500-6373-11eb-8b21-786d23a43311.png)
10일차 까지 완료했습니당

**Comment by dhraudwn** [comment]
![11일차](https://user-images.githubusercontent.com/62053412/106365993-71b95d00-637c-11eb-8c71-8c3a5fe1800f.png)
![12일차](https://user-images.githubusercontent.com/62053412/106365996-72ea8a00-637c-11eb-89bf-4ca149314592.png)
![13일차](https://user-images.githubusercontent.com/62053412/106365997-73832080-637c-11eb-8e5c-a9524aee39d1.png)
11~13일차 입니다ㅏ

**Comment by dhraudwn** [comment]
![14일차](https://user-images.githubusercontent.com/62053412/106394109-4008ca80-643e-11eb-9adc-60d3f5ba99aa.png)
![15일차](https://user-images.githubusercontent.com/62053412/106394111-4139f780-643e-11eb-8bbd-cb85755bfd06.png)
![16일차](https://user-images.githubusercontent.com/62053412/106394112-4139f780-643e-11eb-880f-974cdef0d10d.png)
14~16일차까지 했습니당

**Comment by dhraudwn** [comment]
![17일차](https://user-images.githubusercontent.com/62053412/106670071-e9db8900-65ef-11eb-82ed-abe56de2786c.png)
![19일차](https://user-images.githubusercontent.com/62053412/106670061-e811c580-65ef-11eb-8645-1216d023bf2d.png)
![20일차](https://user-images.githubusercontent.com/62053412/106670066-e8aa5c00-65ef-11eb-8799-f5b06f2436b9.png)
![21일차](https://user-images.githubusercontent.com/62053412/106670068-e942f280-65ef-11eb-9d6d-96da2f696a54.png)
![22일차](https://user-images.githubusercontent.com/62053412/106670070-e942f280-65ef-11eb-9561-6c07cc39bc13.png)
17~22일차!

**Comment by dhraudwn** [comment]
[깃헙](https://github.com/dhraudwn/pybo)
24일차 까지 완료
03-16은 도전1 까지만 했습니다..
